---
abstract: 'Citadel.org protocol coverage'
author:
  - 'Robert Barta <rho@devc.at>, Robert James Clay <jame@rocasa.us>'
build_requires:
  Config::YAML: '1.42'
  Test::More: '0'
  Test::Pod: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Citadel
no_index:
  directory:
    - t
    - inc
requires:
  Readonly: '0'
  perl: '5.006000'
resources:
  repository: https://github.com/jame/Net-Citadel
version: '0.21'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
