--- #YAML:1.0
name:               Net-Citadel
version:            0.20
abstract:           Citadel.org protocol coverage
author:
    - Robert Barta <rho@devc.at>, Robert James Clay <jame@rocasa.us>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Config::YAML:  1.42
    Test::More:    0
    Test::Pod:     0
requires:
    Readonly:  0
resources:
    repository:  https://github.com/jame/Net-Citadel
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
